### ISSUE TITLE
Indent mismatch backtrace 

### ISSUE THREAD

**Issue by k0kubun** [eagletmt/faml#13]
## haml
If haml has a syntax error, it shows a line which includes the error.
I think it is useful to detect a mistake easily.

![](http://i.gyazo.com/66480d9dc3db24eab1ba98b23ede02b3.png)

## faml
Because IndentMismatch is raised on compile time, the backtrace is not shown.
In addition to that, the line number of `where line # raised` is empty.

![](http://i.gyazo.com/fa9a6d79a167ee185ab74f32444d8821.png)

**Comment by eagletmt** [comment]
Other compile time exceptions like Faml::SyntaxError have the same problem.
I'll fix it.

**Comment by eagletmt** [comment]
Fixed IndentMismatch and SyntaxError case and released as v0.2.6.

**Comment by k0kubun** [comment]
quick fix!
+1
