### ISSUE TITLE
Similar gem hamlit

### ISSUE THREAD

**Issue by felixbuenemann** [eagletmt/faml#17]
I've recently stumbled over [hamlit](https://github.com/k0kubun/hamlit), another haml implementation based on temple, which has worked fine for me so far.

Maybe you should think/talk about joining forces?

**Comment by eagletmt** [comment]
Actually the author of hamlit is my colleague :laughing: 
I didn't know he's developing the similar gem until a few days ago.

**Comment by felixbuenemann** [comment]
Well that should make collaboration easy :-)

**Comment by Silex** [comment]
@eagletmt: what was the result of that discussion? it sounds silly to have two gems with almost exactly the same features/goals.

**Comment by k0kubun** [comment]
> two gems with almost exactly the same features/goals.

Not exactly. There is spec difference between Faml and Hamlit: 
https://github.com/k0kubun/hamlit/blob/v2.0.1/REFERENCE.md#limited-boolean-attributes

Maybe Faml tends to be more compatible than Hamlit and Hamlit tends to be aggressive for optimization.
