### ISSUE TITLE
Id is not flattened

### ISSUE THREAD

**Issue by k0kubun** [eagletmt/faml#40]
```html
$ cat in.haml
%span{id: ['foo', ['bar']] }

$ haml in.haml
<span id='foo_bar'></span>

$ faml render in.haml
<span id='foo_[&quot;bar&quot;]'></span>
```

**Comment by eagletmt** [comment]
:dizzy_face:

**Comment by eagletmt** [comment]
Flattening is clearly documented, but I didn't know that.
http://haml.info/docs/yardoc/file.REFERENCE.html#class-and-id-attributes

> The array will first be flattened and any elements that do not test as true will be removed.
